# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
style:
    - '(style: format code with Prettier)'
deepsource: 
    - '(style: format code with Prettier)'
enhancement:
    - '(functionality)'
documentation:
    - '(documentation)'
