style:
    - "(style: format code with Prettier)"
deepsource:
    - "(style: format code with Prettier)"
enhancement:
    - "(functionality)"
documentation:
    - "(documentation)"
    - changed-files:
          - any-glob-to-any-file: "**/*.md"
