version = 1

exclude_patterns = [
  "components/ui/**"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser"
  ]

[[transformers]]
name = "prettier"

